[build]
builder = "dockerfile"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
# JAGeocoder database will be downloaded automatically
JAGEOCODER_DB_PATH = "/app/jageocoder_data"
PORT = "8000"
PYTHONUNBUFFERED = "1"

# Optional: Enable debug logging
JAGEOCODER_DEBUG = "false"

# Memory and CPU settings for large address database
[resources]
memory = "2GB"
cpu = "1"

[volumes]
# Persistent storage for the downloaded address database
jageocoder_data = "/app/jageocoder_data"
